// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ockvxlncsrlrzeyawuas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ja3Z4bG5jc3JscnpleWF3dWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjY5NzUsImV4cCI6MjA3MDA0Mjk3NX0.hPQaqFxjWadTFzSp8N8R0oqnQjNf-fufkXWKCjldRwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});